apiVersion: v1
kind: Service
metadata:
  name: example-app-service
spec:
  ports:
    - port: 7000
      targetPort: 7000
  selector:
    app: example-app-service
  type: NodePort
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: example-app-service
spec:
  selector:
    matchLabels:
      app: example-app-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: example-app-service
    spec:
      containers:
      - image: angular-node-mysql:1.0
        name: angular-node-mysql
        ports:
        - containerPort: 7000
          name: example-app